//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerSpatialTypes.Toolkit.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTEMENT
    {
        public int ID { get; set; }
        public string ID_GEOFLA { get; set; }
        public string CODE_DEPT { get; set; }
        public string NOM_DEPT { get; set; }
        public string CODE_REG { get; set; }
        public string NOM_REG { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
